### PR TITLE
Creation funtion tostring of the person class

### PR DESCRIPTION
**Pull request by DiegoPaez2**
## This PR is a 
- [ ] **Bug Fix**
- [ ] **New Feature** 
- [x] **Breaking Change**

### CODE REVIEW

**Review by Antoni30 — APPROVED** [review]
nice

**Review by sdiegx — CHANGES_REQUESTED** [review]
Delete 16 and 17 lines

**Review by Antoni30 — APPROVED** [review]
listo revisado

**Review by sdiegx — APPROVED** [review]
Good work

**Pull request merged**
